spring.application.name=forge
logging.file.name=logs/dev.log
server.port=8080
springdoc.swagger-ui.path=/api
spring.messages.encoding=UTF-8

# SNCF / Navitia API
sncf.api.key=${SNCF_API_KEY}

# Swagger UI behind HTTPS proxy
server.forward-headers-strategy=framework
